apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: to-do-app
          image: todo1-fravf4hkffbshdbc.azurecr.io/to-do-app:latest
          ports:
            - containerPort: 8080
