apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-app
        # The image will be updated by the Jenkins pipeline
        image: your-docker-repo/gitops-app:latest
        ports:
        - containerPort: 80
